In [163]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
# Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
# score
from sklearn.metrics import f1_score

In [215]:
train_ds=pd.read_csv(r'C:\\Users\\79375\\Desktop\\DS\\sber\\train.csv')
test_ds=pd.read_csv(r'C:\\Users\\79375\\Desktop\\DS\\sber\\sample_submission.csv')

# Data processing

In [216]:
test_ds['user_id'] = test_ds['id'].apply(lambda x: int(x.split(';')[0]))
test_ds['cart'] = test_ds['id'].apply(lambda x: int(x.split(';')[1]))
test_ds.drop('id', axis=1, inplace=True)
train_ds.drop('order_completed_at', axis=1, inplace=True)
train_ds['target'] = train_ds.duplicated(keep=0).apply(lambda x: 1 if x == 1 else 0)

In [217]:
test_ds.iloc[0]['cart']

133

In [218]:
def data_processing(train_ds,test_ds,user_id):
    
    x_train=train_ds[train_ds['user_id']==user_id]
    x_train=x_train.drop_duplicates('cart')
    x_train=x_train.drop(['target','user_id'],axis=1)
    
    y_train=train_ds[train_ds['user_id']==user_id]
    y_train=y_train.drop_duplicates('cart')
    y_train=y_train.drop(['user_id','cart'],axis=1)
    
    x_test=test_ds[test_ds['user_id']==user_id]
    x_test=x_test.drop_duplicates('cart')
    x_test=x_test.drop(['target','user_id'],axis=1)
    
    y_test=test_ds[test_ds['user_id']==user_id]
    y_test=y_test.drop_duplicates('cart')
    y_test=y_test.drop(['cart','user_id'],axis=1)
    return x_train,y_train,x_test,y_test

# Secondary functions

In [219]:
def procent(id_tuple_test):
    progress=id_tuple_test.count()
    i=0
    procent=[]
    while i <=100 :
        procent.append(int(round((progress/100)*i,0)))
        i+=1
    return procent

In [220]:
def scv_submiss(predictions, files_name='Standart_name'):
    id_cart=test_ds.user_id.apply(str) + ';' + test_ds.cart.apply(str)
    submission = pd.DataFrame({'id': id_cart, 'target': predictions})
    submission.to_csv(files_name+'.csv', index=False)

# Building a model map

In [221]:
id_tuple=pd.Series(train_ds['user_id'].drop_duplicates())
id_tuple=id_tuple.sort_values()

In [222]:
def building_model_map(Clussifaer_model,id_users):
    point=0
    progress=procent(id_tuple)
    users_models=[]
    proc=1
    for user_id in id_users:
        x_train,y_train,x_test,y_test=data_processing(train_ds,test_ds,user_id)
        model=Clussifaer_model
        model.fit(x_train,y_train)
        users_models.append(model)
        if point in progress:
            clear_output()
            print(proc,' %')
            proc+=1
        point+=1
        
    return users_models

In [223]:
clussifaer=DecisionTreeClassifier()
model_map=building_model_map(clussifaer,id_tuple)

100  %


# Predict and sample submission

In [224]:
def predict_model(map_model,id_tuple_for_test):
    progress=procent(id_tuple_test)
    point=0
    proc=1
    global_predict=[]
    item_predict=0
    for user_id in id_tuple_for_test:
        x_train,y_train,x_test,y_test=data_processing(train_ds,test_ds,user_id)
        castomer_predict=map_model[user_id].predict(x_test)
        global_predict.append(castomer_predict)
        if point in progress:
            clear_output()
            print(proc,' %')
            proc+=1
        point+=1
    return global_predict

In [225]:
id_tuple_test=pd.Series(test_ds['user_id'])
id_tuple_test=id_tuple_test.drop_duplicates()


In [226]:
Global_predict=predict_model(model_map,id_tuple_test)

100  %


In [229]:
Global_predict

[array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       dtype=int64),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1], dtype=int64),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 

In [227]:
Global_predict1=[]
for i in Global_predict:
    for j in i:
        Global_predict1.append(j)

In [ ]:
y_test=test_ds['target']
f1_score(y_test,Global_predict)

In [ ]:
scv_submiss(Global_predict, files_name='New_meta_kNN_model'):